import { Inter } from 'next/font/google'
import './globals.css'
import BtnDashboard from "./components/dashboard/btn-dashboard/buttonDash";
import Dashboard from "./dashboard/page";
import BtnSocial from "./components/dashboard/btn-social/buttonSocial"

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
	  
		<Dashboard>
			<BtnDashboard/>
			<BtnSocial/> 
		</Dashboard>
		
			{children}
			
        </body>
    </html>
  )
}
